export const products = [
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0001',
		quantity: '33',
		remains: '10',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '43610',
		costPrice: '35000',
		markUp: '8610',
		gender: 'Женский',
		name: 'DISCO',
		linkName: 'disco',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'графитовый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		frameGrowth: '13',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '09.07.2024',
			disposalTime: '12:00',
			fromWarehouse: 'Основной склад',
			organization: 'Вело Мото & Drive'
		}
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0002',
		quantity: '45',
		remains: '20',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 2 до 5 лет',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '28000',
		costPrice: '21000',
		markUp: '7000',
		gender: 'Мужской',
		name: 'QUEST DISC 29',
		linkName: 'quest_disc_29',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'черный',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '23',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые механические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '10.07.2024',
			disposalTime: '10:00',
			fromWarehouse: 'Основной склад',
			organization: 'Вело Мото & Drive'
		}
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0003',
		quantity: '15',
		remains: '10',
		type: 'Мопеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 3 до 6 лет',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33026',
		costPrice: '29000',
		markUp: '4026',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29',
		linkName: 'rocky_2.0_disc_29',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '28',
		color: 'синий',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '23',
		frameGrowth: '17',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Ножной тормоз Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '09.00.2009',
			disposalTime: '09:09',
			fromWarehouse: 'Основной склад',
			organization: 'Вело Мото & Drive'
		}
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0004',
		quantity: '40',
		remains: '15',
		type: 'Мопеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'От 5 до 8 лет',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '48120',
		costPrice: '39000',
		markUp: '9120',
		gender: 'Женский',
		name: 'DISCO_v2',
		linkName: 'disco2',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'розовый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '4',
		frameGrowth: '20',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0005',
		quantity: '50',
		remains: '5',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		ageGroup: 'Подростковый',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '24050',
		costPrice: '19000',
		markUp: '5050',
		gender: 'Мужской',
		name: 'QUEST DISC 29_v2',
		linkName: 'quest_disc_29_2',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'фиолетовый',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '19',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0006',
		quantity: '13',
		remains: '3',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 5 до 8 лет',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33176',
		costPrice: '27000',
		markUp: '6176',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v2',
		linkName: 'rocky_2.0_disc_29_2',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '28',
		color: 'голубой',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '12',
		frameGrowth: '14',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'U-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Жесткая вилка',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0007',
		quantity: '65',
		remains: '12',
		type: 'Квадроциклы',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'От 3 до 6 лет',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '43044',
		costPrice: '36000',
		markUp: '7044',
		gender: 'Женский',
		name: 'DISCO_v3',
		linkName: 'disco3',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'оранжевый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		frameGrowth: '16',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'V-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0008',
		quantity: '35',
		remains: '30',
		type: 'Квадроциклы',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 2 до 5 лет',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '28052',
		costPrice: '21000',
		markUp: '7052',
		gender: 'Мужской',
		name: 'QUEST DISC 29_v3',
		linkName: 'quest_disc_29_3',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'желтый',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '21',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний V-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Жесткая вилка',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0009',
		quantity: '44',
		remains: '24',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '26000',
		markUp: '7666',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v3',
		linkName: 'rocky_2.0_disc_29_3',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '28',
		color: 'зеленый',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '27',
		frameGrowth: '18',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0010',
		quantity: '37',
		remains: '33',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '23000',
		markUp: '10666',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v3',
		linkName: 'rocky_2.0_disc_29_3',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '16',
		color: 'зеленый',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '20',
		frameGrowth: '15',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0011',
		quantity: '20',
		remains: '20',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '43610',
		costPrice: '30000',
		markUp: '13610',
		gender: 'Женский',
		name: 'DISCO',
		linkName: 'disco',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'графитовый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		frameGrowth: '13',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0012',
		quantity: '30',
		remains: '25',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 2 до 5 лет',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '28000',
		costPrice: '21000',
		markUp: '7000',
		gender: 'Мужской',
		name: 'QUEST DISC 29',
		linkName: 'quest_disc_29',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'черный',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '23',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые механические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0013',
		quantity: '10',
		remains: '10',
		type: 'Мопеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 3 до 6 лет',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33026',
		costPrice: '25000',
		markUp: '8026',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29',
		linkName: 'rocky_2.0_disc_29',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '28',
		color: 'синий',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '23',
		frameGrowth: '17',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Ножной тормоз Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0014',
		quantity: '25',
		remains: '10',
		type: 'Мопеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'От 5 до 8 лет',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '48120',
		costPrice: '37000',
		markUp: '11120',
		gender: 'Женский',
		name: 'DISCO_v2',
		linkName: 'disco2',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'розовый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '4',
		frameGrowth: '20',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-18'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0015',
		quantity: '35',
		remains: '27',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		ageGroup: 'Подростковый',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '24050',
		costPrice: '19000',
		markUp: '5050',
		gender: 'Мужской',
		name: 'QUEST DISC 29_v2',
		linkName: 'quest_disc_29_2',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'фиолетовый',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '19',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-09'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0016',
		quantity: '20',
		remains: '17',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 5 до 8 лет',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33176',
		costPrice: '21000',
		markUp: '12176',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v2',
		linkName: 'rocky_2.0_disc_29_2',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '20',
		color: 'желтый',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '12',
		frameGrowth: '13',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'U-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Жесткая вилка',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-04'
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0017',
		quantity: '55',
		remains: '30',
		type: 'Квадроциклы',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'От 3 до 6 лет',
		discount: '18%',
		originalPrice: '53000',
		currentPrice: '43044',
		costPrice: '36000',
		markUp: '7044',
		gender: 'Женский',
		name: 'DISCO_v3',
		linkName: 'disco3',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'оранжевый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		frameGrowth: '16',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'V-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Двухподвес',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-30'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0018',
		quantity: '30',
		remains: '20',
		type: 'Квадроциклы',
		category: 'ГОРНЫЙ',
		ageGroup: 'От 2 до 5 лет',
		discount: '18%',
		originalPrice: '36400',
		currentPrice: '28052',
		costPrice: '21000',
		markUp: '7052',
		gender: 'Мужской',
		name: 'QUEST DISC 29_v3',
		linkName: 'quest_disc_29_3',
		description:
			'Aist Quest MD 29″ — горный велосипед для любителей активного образа жизни. Аист Квест на 29″ колесах замечательно подойдет для использования как в городских условиях, так и на легком бездорожье. Модель универсально и обеспечивает максимальный комфорт и надежность в любых условиях. Достоинством горного велосипеда является наличие амортизационной вилки, которая поглотит вибрации от езды по бугристой, неровной поверхности. Наличие системы скоростей позволит велосипедисту контролировать ход велосипеда на любой дороге и упростит преодоление горочки. А невероятно современный, яркий дизайн придает велосипеду стильный и неповторимый образ. Основные параметры горного велосипеда Аист Квест: Прочность конструкции велосипеда обеспечивает рама из стали, которая способна с легкостью выдержать внушительные нагрузки. 21 ступенчатая система скоростей позволяет контролировать ход велосипеда. Система амортизации — идеальный вариант для агрессивного бездорожья. Надежные дисковые тормоза максимально эффективны на бездорожье и имеют малый тормозной путь. Универсальные покрышки обеспечивают высокую проходимость в любых условиях. Заказать и купить горный велосипед Аист Квест с доставкой просто, ведь магазин Верос осуществляет доставку велосипедов в собранном и профессионально настроенном виде.',
		wheelsSize: '25',
		color: 'желтый',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		frameGrowth: '21',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний V-brake Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Жесткая вилка',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-12'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0019',
		quantity: '44',
		remains: '40',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '27000',
		markUp: '6666',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v3',
		linkName: 'rocky_2.0_disc_29_3',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '28',
		color: 'зеленый',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '27',
		frameGrowth: '18',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '00.00.0000',
			disposalTime: '00:00',
			fromWarehouse: 'Вселенная',
			organization: 'Космос'
		},
		dateSale: '2024-06-01'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0020',
		quantity: '50',
		remains: '10',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		ageGroup: 'Для взрослых',
		discount: '18%',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '24000',
		markUp: '9666',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29_v3',
		linkName: 'rocky_2.0_disc_29_3',
		description:
			'Горный велосипед для активной езды по пересеченной местности. Благодаря алюминиевой раме он легкий и крепкий. Амортизационная вилка смягчает неровности, и ехать на нем комфортнее. Способен выдержать высокие нагрузки. Крепкие и прочные дисковые механические тормоза делают свое дело отлично, и безопасность возрастает при любом торможении. За счет больших колес нужно меньше затрачивать сил для движения.',
		wheelsSize: '16',
		color: 'зеленый',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '20',
		frameGrowth: '15',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Передний клещевой Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C',
		amor: 'Хардтейл',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '10.07.2012',
			disposalTime: '11:00',
			fromWarehouse: 'Основной склад',
			organization: 'Вело Мото & Drive'
		},
		dateSale: '2024-06-11'
	}
]

export const productsQ = [
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0010',
		quantity: '37',
		remains: '33',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '23000',
		markUp: '10666',
		name: 'ROCKY 2.0 DISC 29_v3',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0011',
		quantity: '20',
		remains: '20',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		originalPrice: '53000',
		currentPrice: '43610',
		costPrice: '30000',
		markUp: '13610',
		name: 'DISCO',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0012',
		quantity: '30',
		remains: '25',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		originalPrice: '36400',
		currentPrice: '28000',
		costPrice: '21000',
		markUp: '7000',
		name: 'QUEST DISC 29',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0013',
		quantity: '10',
		remains: '10',
		type: 'Мопеды',
		category: 'ГОРНЫЙ',
		originalPrice: '40440',
		currentPrice: '33026',
		costPrice: '25000',
		markUp: '8026',
		name: 'ROCKY 2.0 DISC 29',
		writtenOff: false,
		additionalDetails: false
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0014',
		quantity: '25',
		remains: '10',
		type: 'Мопеды',
		category: 'ГОРОДСКОЙ',
		originalPrice: '53000',
		currentPrice: '48120',
		costPrice: '37000',
		markUp: '11120',
		name: 'DISCO_v2',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-18'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0015',
		quantity: '35',
		remains: '27',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		originalPrice: '36400',
		currentPrice: '24050',
		costPrice: '19000',
		markUp: '5050',
		name: 'QUEST DISC 29_v2',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-09'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0016',
		quantity: '20',
		remains: '17',
		type: 'Самокаты',
		category: 'ГОРНЫЙ',
		originalPrice: '40440',
		currentPrice: '33176',
		costPrice: '21000',
		markUp: '12176',
		name: 'ROCKY 2.0 DISC 29_v2',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-04'
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		code: '0017',
		quantity: '55',
		remains: '30',
		type: 'Квадроциклы',
		category: 'ГОРОДСКОЙ',
		originalPrice: '53000',
		currentPrice: '43044',
		costPrice: '36000',
		markUp: '7044',
		name: 'DISCO_v3',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-30'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		code: '0018',
		quantity: '30',
		remains: '20',
		type: 'Квадроциклы',
		category: 'ГОРНЫЙ',
		originalPrice: '36400',
		currentPrice: '28052',
		costPrice: '21000',
		markUp: '7052',
		name: 'QUEST DISC 29_v3',
		writtenOff: false,
		additionalDetails: false,
		dateSale: '2024-06-12'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0019',
		quantity: '44',
		remains: '40',
		type: 'Велосипеды',
		category: 'ГОРНЫЙ',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '27000',
		markUp: '6666',
		name: 'ROCKY 2.0 DISC 29_v3',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '00.00.0000',
			disposalTime: '00:00',
			fromWarehouse: 'Вселенная',
			organization: 'Космос'
		},
		dateSale: '2024-06-01'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		code: '0020',
		quantity: '50',
		remains: '10',
		type: 'Велосипеды',
		category: 'ГОРОДСКОЙ',
		originalPrice: '40440',
		currentPrice: '33666',
		costPrice: '24000',
		markUp: '9666',
		name: 'ROCKY 2.0 DISC 29_v3',
		writtenOff: true,
		additionalDetails: {
			disposalDate: '10.07.2012',
			disposalTime: '11:00',
			fromWarehouse: 'Основной склад',
			organization: 'Вело Мото & Drive'
		},
		dateSale: '2024-06-11'
	}
]

export const Colors = {
	черный: '#000',
	графитовый: '#636d82',
	синий: '#0000FF',
	белый: '#fff',
	желтый: '#eded49',
	оранжевый: '#f2ac21',
	красный: '#dd3333',
	зеленый: '#81d742',
	голубой: '#25dced',
	серый: '#bcbcbc',
	фиолетовый: '#8224e3',
	розовый: '#fca4d7'
}

export const types = ['Велосипеды','Мопеды','Самокаты','Квадроциклы','Мотоциклы']
